# The nextstrain/base Dockerfile is a multi-stage with both a "builder" target
# and a main target. To enable proper caching via --cache-from we need both
# these images available to pull layers from. This means pulling both in at the
# start and pushing both up at the end.
# Calling `docker run nextstrain/base` will still only pull down the small base image
# rather than pulling down the larger nextstrain/base-builder image
services:
  - docker
sudo: required
before_install:
  - export DATESTRING=$(date +%F-%H-%M-%S)
  - docker pull nextstrain/base-builder
  - docker pull nextstrain/base
install:
  - |
    docker build --build-arg CACHE_DATE=$DATESTRING \
      --cache-from nextstrain/base-builder \
      --cache-from nextstrain/base \
      -t nextstrain/base-builder:latest --target builder .
  - |
    docker build --build-arg CACHE_DATE=$DATESTRING \
      --cache-from nextstrain/base-builder \
      --cache-from nextstrain/base \
      -t nextstrain/base:latest .
script:
  - echo "Build finished"
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_LOGIN --password-stdin;
      docker push nextstrain/base-builder:latest;
      docker push nextstrain/base:latest;
      docker tag nextstrain/base-builder:latest nextstrain/base-builder:$DATESTRING;
      docker tag nextstrain/base:latest nextstrain/base:$DATESTRING;
      docker push nextstrain/base-builder:$DATESTRING;
      docker push nextstrain/base:$DATESTRING;
    fi
