#!/bin/bash
set -euo pipefail

# The default is to run the local data dev server, but any of the package.json
# "scripts" can be run by giving their name.
if [[ $# -eq 0 ]]; then
    set -- start:local
fi

cd /nextstrain/auspice
exec npm run "$@"
