#!/bin/bash
set -euo pipefail

# The default is to run the non-dev server with local data, but any of the
# package.json "scripts" can be run by giving their name and args.
if [[ $# -eq 0 ]]; then
    set -- server:local
fi

cd /nextstrain/auspice
exec npm run "$@"
