#!/bin/bash
#
# Get the target triple from a Docker target platform.
#
# The Docker target platform is provided by the TARGETPLATFORM variable¹.
# ¹ https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope
#
set -euo pipefail

if [[ $# -gt 0 ]]; then
    TARGETPLATFORM="$1"
fi

case $TARGETPLATFORM in
    "linux/amd64")
        echo "x86_64-unknown-linux-gnu"
        ;;
    "linux/arm64")
        echo "aarch64-unknown-linux-gnu"
        ;;
    *)
        echo "No target triple mapping for $TARGETPLATFORM." 1>&2
        exit 1
        ;;
esac
