#!/bin/bash
#
# Builds the nextstrain/base and nextstrain/base-builder images with useful
# caching.
#
# Set CACHE_DATE in your environment to force layers after our custom cache
# point to be re-built. See the ARG CACHE_DATE line in the Dockerfile for more
# information.
#
set -euo pipefail


# The nextstrain/base Dockerfile is a multi-stage with both a "builder" target
# and a main target.  To enable proper caching via --cache-from we need both
# these images available to pull layers from.  This means pulling both in at
# the start and pushing both up at the end.
#
# Calling `docker run nextstrain/base` will still only pull down the small base
# image rather than pulling down the larger nextstrain/base-builder image.

docker build \
    --build-arg CACHE_DATE \
    --cache-from nextstrain/base-builder \
    --cache-from nextstrain/base \
    --tag nextstrain/base-builder \
    --target builder \
    .

docker build \
    --build-arg CACHE_DATE \
    --cache-from nextstrain/base-builder \
    --cache-from nextstrain/base \
    --tag nextstrain/base \
    .
