#!/bin/bash
#
# Outputs the Git tag for the latest stable release of Augur, supplanting the
# old "release" branch which no longer exists.
#
# By convention/process we make Git tags for each version released to PyPI, so
# query PyPI's index for the latest stable version and emit that as-is.
#
set -euo pipefail

curl -fsSL https://pypi.org/pypi/nextstrain-augur/json | jq -r .info.version
