#!/bin/bash
#
# Pull the nextstrain/base and nextstrain/base-builder images from Docker Hub.
#
# By default this fetches the "latest" tag, but you can provide other tags in
# addition to or instead of "latest".
#
set -euo pipefail

# If no tags are given, default to "latest".
if [[ $# -eq 0 ]]; then
    set -- latest
fi

for tag in "$@"; do
    docker pull nextstrain/base-builder:$tag
    docker pull nextstrain/base:$tag
done
