#!/bin/bash
#
# Push the nextstrain/base and nextstrain/base-builder images to Docker Hub.
#
# By default this publishes the "latest" tag, but you can provide other tags in
# addition to or instead of "latest".
#
set -euo pipefail

# If no tags are given, default to "latest".
if [[ $# -eq 0 ]]; then
    set -- latest
fi

for tag in "$@"; do
    docker push nextstrain/base-builder:$tag
    docker push nextstrain/base:$tag
done
