#!/bin/bash
#
# Push the nextstrain/base and nextstrain/base-builder images to Docker Hub.
#
# By default this publishes the "latest" tag, but you can provide other tags in
# addition to or instead of "latest".
#
set -euo pipefail

# If no tags are given, default to "latest".
if [[ $# -eq 0 ]]; then
    set -- latest
fi

BASE_IMAGE="nextstrain/base"
BASE_BUILDER_IMAGE="nextstrain/base-builder"

for tag in "$@"; do
    docker push $BASE_BUILDER_IMAGE:$tag
    docker push $BASE_IMAGE:$tag
done
