#!/bin/bash
#
# Push the nextstrain/base and nextstrain/base-builder images to Docker Hub.
#
# By default this publishes the "latest" tag, but you can provide other tags in
# addition to or instead of "latest".
#
# Errors if any of the tagged images have already been pushed.
#
set -euo pipefail

# If no tags are given, default to "latest".
if [[ $# -eq 0 ]]; then
    set -- latest
fi

BUILDER_IMAGE=nextstrain/base-builder
FINAL_IMAGE=nextstrain/base

for tag in "$@"; do
    if [[ $(docker image inspect --format "{{.RepoDigests}}" $BUILDER_IMAGE:$tag) != '[]' || $(docker image inspect --format "{{.RepoDigests}}" $FINAL_IMAGE:$tag) != '[]' ]]; then
        echo "At least one of $BUILDER_IMAGE:$tag and $FINAL_IMAGE:$tag has already been pushed. This can happen if the newly built image is not available in the local registry." >&2
        exit 1
    fi
done

for tag in "$@"; do
    docker push "$BUILDER_IMAGE:$tag"
    docker push "$FINAL_IMAGE:$tag"
done
