#!/bin/bash
#
# Assign the given additional tags to the nextstrain/base:latest and
# nextstrain/base-builder:latest images.
# Errors if a tagged image has already been pushed.
#
set -euo pipefail

if [[ $# -eq 0 ]]; then
    echo "Please provide at least one new tag." >&2
    exit 1
fi

BASE_IMAGE="nextstrain/base"
BASE_BUILDER_IMAGE="nextstrain/base-builder"

for tag in "$@"; do
    docker tag $BASE_BUILDER_IMAGE:{latest,$tag}
    docker tag $BASE_IMAGE:{latest,$tag}
done
