#!/bin/bash
#
# Assign the given additional tags to the nextstrain/base:latest and
# nextstrain/base-builder:latest images.
#
set -euo pipefail

if [[ $# -eq 0 ]]; then
    echo "Please provide at least one new tag." >&2
    exit 1
fi

for tag in "$@"; do
    docker tag nextstrain/base-builder:{latest,$tag}
    docker tag nextstrain/base:{latest,$tag}
done
