#!/bin/bash
#
# Assign the latest tag to the nextstrain/base:$tag and
# nextstrain/base-builder:$tag images.
#
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Please provide a tag." >&2
    exit 1
fi

tag="$1"

FINAL_IMAGE=nextstrain/base
BUILDER_IMAGE=nextstrain/base-builder

docker tag "$BUILDER_IMAGE":{"$tag",latest}
docker tag "$FINAL_IMAGE":{"$tag",latest}
