#!/bin/bash
#
# Assign the latest tag to the nextstrain/base:$tag and
# nextstrain/base-builder:$tag images.
#
set -euo pipefail

if [[ $# -ne 1 ]]; then
    echo "Please provide a tag." >&2
    exit 1
fi

tag="$1"

BASE_IMAGE=nextstrain/base
BASE_BUILDER_IMAGE=nextstrain/base-builder

docker tag "$BASE_BUILDER_IMAGE":{"$tag",latest}
docker tag "$BASE_IMAGE":{"$tag",latest}
